[package]
name = "state_design_pattern"
version = "0.1.0"
authors = ["[maciej] <[md9u17@soton.ac.uk]>"]
edition = "2018"

[lib]
name = "blog"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

